build:
command: npm run build
commandOrigin: ui
publish: /opt/build/repo/dist
publishOrigin: ui
functions:
'*':
external_node_modules:
- express
node_bundler: esbuild
functionsDirectory: /opt/build/repo/netlify/functions
redirects:
- force: true
from: /api/*
      status: 200
      to: /.netlify/functions/api/:splat
  redirectsOrigin: config
